### ISSUE TITLE
IndexError: vector

### ISSUE THREAD

**Issue by benmaier** [gstonge/SamplableSet#29]
Hi, I've gotten this error for the first time since I've started using SamplableSet, any idea what might cause this?

```
/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/SamplableSet/_wrapper.py in sample(self, n_samples, replace)
    140         """
    141         if n_samples == 1:
--> 142             x = self._samplable_set.sample()
    143             if not replace and x is not None:
    144                 self._samplable_set.erase(x[0])

IndexError: vector
```

**Comment by benmaier** [comment]
note: It happens very rarely and I'm currently trying to find out under which conditions

**Comment by gstonge** [comment]
This might be related to #15. What are the minimum and maximum weight you are using? It is possible that there are some round-off errors that accumulate in the tree structure. When possible, use the `clear` method if the set is empty. If the error still happens, we might need to implement some automated check-up on the tree structure to make sure that round-off errors do not cause these runtime errors.

**Comment by benmaier** [comment]
Yes, I think that's what's happening. I'm usually checking whether or not "total_weight" is zero and sample from the set if this is not the case. However, I'm inserting and deleting like crazy, so I think it happens that small errors accumulate and when the set is empty, the total weight is still 1e-11 or sth like that. In this case, I get the error above.

**Comment by gstonge** [comment]
In the latest version, there is an `empty` method that checks the number of elements instead, or `size` could be used also. These are not susceptible to rounding errors. When you find that the set is empty, use the `clear` after to remove all remaining rounding errors in the tree. That might help.

**Comment by benmaier** [comment]
awesome, thanks!
